### PR TITLE
updates for V03-00-08

### PR DESCRIPTION
**Pull request by Sam-Harper**
these are the updates for V03-08-08

They are:
  * proxy support for browser converter which is used by hltGetConfiguration and friends
  * preventing a menu which has a module on a task and also directly on a path/sequence from being saved
  * update deploy script to add sha512 hashes of the files when deploying

### CODE REVIEW

**Comment by fwyzard** [comment]
Rather than computing a checksum of the content of the (compiled) code, you could simply reuse the git hash.

**Comment by Sam-Harper** [comment]
yep just saw your comment on mattermost (I'm getting a lot of lag there)

**Comment by fwyzard** [comment]
no problem, I commented in both places almost at the same time, I hadn't seem the comments on Mattermost earlier

**Comment by Sam-Harper** [comment]
so it now appends the git hash to the version number for non-production versions which we can then query and download. 

The script is now integrates more with git (now it'll deploy based on branch name so no accidently deploying beta to production) 

This does have the downside that because the version number is not enforced by code to be changed for production, we could end up in the werid situation where we accidently push the same version numbers and thus prevent a remote update.  Its a series of bugs and operational mistakes but if its not forbidden programatically, it will happen and will be painful to debug in 2 years time. 

Actually haven written this all out, I think I'll append the git hash always to the website and we can always download that and check that that. However the git hash is only added to the actual version number of the pre-release versions.

**Pull request merged**
