### PR TITLE
`JavaCodeExecution`: added `customiseForCMSHLT2651`

### PR DESCRIPTION
**Pull request by missirol**
Adds customisation function to apply the changes described in [CMSHLT-2651](https://its.cern.ch/jira/browse/CMSHLT-2651).

By default, this new customisation function is not enabled.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
Sorry, but shouldn't 73 be used instead of 72?

**Comment by missirol** [comment]
I'm not sure what you mean. What is "73" ?

**Comment by Martin-Grunewald** [comment]
72 and 73 are the PRs you just made...

**Comment by missirol** [comment]
https://github.com/cms-sw/hlt-confdb/pull/72 adds a customisation to edit the current combined table, and complete [CMSHLT-2651](https://its.cern.ch/jira/browse/CMSHLT-2651).

https://github.com/cms-sw/hlt-confdb/pull/73 changes what is used when a _new_ OutputModule (stream) is added while editing menus. It ensures that, when new streams are added in the future, they will have the new default settings (and not the old ones).

**Pull request merged**
